name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/flutter_web_python/**'
      - '.github/workflows/docker.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/flutter-frontend
      API_URL: http://backend:5000/api/transcribe
      CORS_ORIGIN: http://localhost:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/flutter_web_python
          file: ./frontend/flutter_web_python/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          build-args: |
            API_URL=${{ env.API_URL }}
            CORS_ORIGIN=${{ env.CORS_ORIGIN }}
